version: "3.9"
services:
  frontend:
    networks:
      - frontend
    container_name: container-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: image-frontend
    env_file:
      - .env
    ports:
      - 8081:80
  backend:
    networks:
      - backend
    container_name: container-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: image-backend
    env_file:
      - .env
    ports:
      - 4000:3000
  postgres:
    networks:
      - backend
    container_name: container-postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  adminer:
    networks:
      - backend
    container_name: container-adminer
    image: adminer
    ports:
      - 8080:8080
volumes:
  postgres_data:
networks:
  frontend:
  backend: